version: '3'

services:
  postgres:
      image: postgres
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ${PSQL_USR}
        POSTGRES_PASSWORD: ${PSQL_PASS}
        
  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: ${PSQL_USR}
        DB_PASSWORD: ${PSQL_PASS}
        KEYCLOAK_USER: ${KEYC_USR}
        KEYCLOAK_PASSWORD: ${KEYC_PASS}
      restart: unless-stopped
      ports:
        - 8181:8080
      depends_on:
        - postgres
        
  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped
    command: "-cleanup=true -ip ${HOST_IP} consul://consul.service.consul:8500"  
 
